numbeo_countries = ['Switzerland', 'Denmark', 'United States', 'Belgium', 'Luxembourg',
       'United Kingdom', 'Israel', 'Canada', 'Norway', 'Netherlands',
       'Ireland', 'Australia', 'Greece', 'Uruguay', 'Cyprus', 'Austria',
       'Italy', 'Malta', 'France', 'Finland', 'New Zealand', 'Germany',
       'Spain', 'Estonia', 'Slovenia', 'Lithuania', 'Sweden', 'Singapore',
       'Portugal', 'Latvia', 'Bulgaria', 'Croatia', 'Montenegro',
       'Albania', 'Hungary', 'Armenia', 'Panama', 'Venezuela',
       'Costa Rica', 'Romania', 'Mexico', 'Georgia', 'Kazakhstan',
       'Hong Kong (China)', 'Azerbaijan', 'Poland', 'Slovakia',
       'Czech Republic', 'Chile', 'Serbia', 'Qatar',
       'United Arab Emirates', 'South Africa', 'Turkey', 'Belarus',
       'Russia', 'Moldova', 'South Korea', 'Jordan', 'Argentina', 'Cuba',
       'Palestine', 'Jamaica', 'Saudi Arabia', 'Japan', 'Kuwait',
       'Mauritius', 'Ukraine', 'Brazil', 'Bosnia And Herzegovina',
       'North Macedonia', 'Oman', 'Uzbekistan', 'Taiwan', 'Colombia',
       'Iraq', 'Libya', 'Peru', 'Iran', 'Kenya', 'Egypt', 'Ecuador',
       'Philippines', 'Morocco', 'China', 'Tunisia', 'Sri Lanka', 'India',
       'Malaysia', 'Bolivia', 'Thailand', 'Algeria', 'Nigeria', 'Vietnam',
       'Nepal', 'Indonesia', 'Bangladesh', 'Pakistan']